### ISSUE TITLE
Upload hung. not sure what to do...

### ISSUE THREAD

**Issue by joncamp** [MSREnable/EyeCatcher#25]
![image](https://user-images.githubusercontent.com/11506084/98044980-a436d680-1ddc-11eb-889d-d627a88d8f22.png)

**Comment by JayBeavers** [comment]
IUploadController doesn't have any interface to report upload failure status as it's occurring, other than incrementing FailedUploadCount.  One issue that is occurring is there is a 1 minute delay after a failed upload in which nothing is happening, but there's no status method to report back 'upload failed, waiting before retry'.  We probably want a simple status string or status enum that the IUploadController can use to send status updates.

We could expose an 'upload tick' event that fires after every 64k chunk is uploaded, to keep a spinner moving while a file upload is in progress.  I don't want to decrement TotalTodo because the upload could fail between chunks and the byte count would be off after a restart.

**Comment by joncamp** [comment]
This seems pretty reasonable (assuming it works). These status bars are always janky in the best of times, but just having a feeling that things are working vs. not would be a nice help.

**Comment by JayBeavers** [comment]
User experience I'm thinking is basically "while Status == Uploading, increment a spinner position every tick", otherwise hide the spinner.

**Comment by peteams** [comment]
As an alternative we could just display a ProgressRing control while there is stuff to be uploaded. There is an branch petea/issue/25 that contains code that adds a ProgressRing at the end of the control that shows background upload progress. The ProgressRing is only shown while there are files to upload.

The same change also moves the background upload control from the bottom line of the user interface just above it. That to allow a helpful 'press the Next button' text to be displayed at the bottom of the display,

**Comment by JayBeavers** [comment]
OK, take a look at the interface changes I've pushed to branch uploadStatus.

**Comment by JayBeavers** [comment]
@peteams ProgressRing is just a binary on/off.  It's not going to address the 'is this hung' issue imho in a way that something that moves when actual progress is made will.

I don't see a xaml 'spin a clock' like control.  The best I could find in a quick search is ProgressBar.

**Comment by peteams** [comment]
The uploadStatus branch looks fine. My only quibble would be passing FailureMessage as a string because it will not be easily localised. Though there is not really a convenient way of doing it other than using an Exception object that might be of our own custom type. 

I don't believe there is a control you can manually spin. As you state, there is the ProgressRing that you can just switch on and off. The ProgressBar is a linear progress control, or "I'm thinking" side-to-side affair. In the Toolkit there is the RadialProgressBar that fills around a circle.

I'm comfortable with a control that just spins regardless of what's going on in the background in the basis that, if the code is correct, the control reflects reality. I can see an argument for having a watchdog timer that gets reset every time an upload event occurs and stops the spinner if it ever fires.

We could also handcraft a control we manually rotated on a tick. That could be by a fixed amount per tick, so it would spin at different speeds depending on how fast ticks occurred. Another implementation would align the amount of rotation to something based on a timeline, so the speed of rotation is always constant, but it is jerkier for lower tick rates. Either way, rotation would stop if Ticking stopped.
